# Generated by Django 5.2.4 on 2025-07-31 08:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonorProfile',
            fields=[
                ('wallet_address', models.CharField(max_length=42, primary_key=True, serialize=False, unique=True)),
                ('ens_name', models.CharField(blank=True, max_length=100)),
                ('total_donated', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('total_points', models.IntegerField(default=0)),
                ('donation_count', models.IntegerField(default=0)),
                ('twitter_handle', models.CharField(blank=True, max_length=50)),
                ('farcaster_username', models.CharField(blank=True, max_length=50)),
                ('is_public', models.BooleanField(default=True)),
                ('receive_updates', models.BooleanField(default=True)),
                ('first_donation_date', models.DateTimeField(blank=True, null=True)),
                ('last_donation_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('homeless', 'Homeless Individual'), ('student', 'Student in Crisis'), ('medical', 'Medical Emergency')], max_length=20)),
                ('description', models.TextField()),
                ('wallet_address', models.CharField(max_length=42, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('verification_proof', models.TextField(blank=True)),
                ('verified_by', models.CharField(blank=True, max_length=100)),
                ('goal_amount', models.DecimalField(decimal_places=8, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('raised_amount', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('image_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('urgency_level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(choices=[('homeless', 'Homeless Individual'), ('student', 'Student in Crisis'), ('medical', 'Medical Emergency')], max_length=20)),
                ('description', models.TextField()),
                ('proof_documents', models.TextField()),
                ('wallet_address', models.CharField(max_length=42)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_by', models.CharField(blank=True, max_length=100)),
                ('review_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('goal_amount', models.DecimalField(decimal_places=8, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))])),
                ('raised_amount', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('bonus_multiplier', models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=3)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipients', models.ManyToManyField(related_name='campaigns', to='core.recipient')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_address', models.CharField(db_index=True, max_length=42)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00001'))])),
                ('tx_hash', models.CharField(max_length=66, unique=True)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('points_earned', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='core.recipient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
