# Generated by Django 5.2.4 on 2025-07-31 18:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pool_type', models.CharField(choices=[('emergency', '🚨 Emergency Fund'), ('community', '🏘️ Community Projects'), ('creators', '🎨 Creator Support'), ('development', '⚡ Platform Development')], max_length=20)),
                ('description', models.TextField()),
                ('wallet_address', models.CharField(max_length=42, unique=True)),
                ('allocation_percentage', models.DecimalField(decimal_places=2, default=0.25, max_digits=3)),
                ('total_raised', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('total_distributed', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('donor_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('emoji', models.CharField(default='💝', max_length=10)),
                ('color', models.CharField(default='blue', max_length=20)),
                ('image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoolDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_address', models.CharField(db_index=True, max_length=42)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('tx_hash', models.CharField(max_length=66, unique=True)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('points_earned', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='core.donationpool')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_address', models.CharField(db_index=True, max_length=42)),
                ('recipient_address', models.CharField(db_index=True, max_length=42)),
                ('recipient_username', models.CharField(blank=True, max_length=100)),
                ('recipient_fid', models.CharField(blank=True, max_length=50)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('message', models.TextField(blank=True, max_length=280)),
                ('tx_hash', models.CharField(max_length=66, unique=True)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('frame_interaction', models.BooleanField(default=False)),
                ('points_earned', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TokenReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('reason', models.CharField(max_length=100)),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('related_donation_tx', models.CharField(blank=True, max_length=66)),
                ('frame_interaction', models.BooleanField(default=False)),
                ('is_claimed', models.BooleanField(default=False)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claim_tx_hash', models.CharField(blank=True, max_length=66)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('wallet_address', models.CharField(max_length=42, primary_key=True, serialize=False, unique=True)),
                ('farcaster_username', models.CharField(blank=True, max_length=100)),
                ('farcaster_fid', models.CharField(blank=True, max_length=50)),
                ('ens_name', models.CharField(blank=True, max_length=100)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True, max_length=280)),
                ('avatar_url', models.URLField(blank=True)),
                ('total_donated', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('total_received', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('total_points', models.IntegerField(default=0)),
                ('donation_count', models.IntegerField(default=0)),
                ('is_public_profile', models.BooleanField(default=True)),
                ('accepts_donations', models.BooleanField(default=True)),
                ('donation_message', models.CharField(blank=True, default='Thanks for your support! 💙', max_length=100)),
                ('tokens_earned', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('tokens_claimed', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('first_donation_date', models.DateTimeField(blank=True, null=True)),
                ('last_donation_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='donationcampaign',
            name='recipients',
        ),
        migrations.DeleteModel(
            name='VerificationRequest',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='farcaster_username',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='receive_updates',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='twitter_handle',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='location',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='urgency_level',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='verification_date',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='verification_proof',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='verified_by',
        ),
        migrations.AddField(
            model_name='donation',
            name='migrated_to_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='migrated_to_social',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='migrated_to_user_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=18),
        ),
        migrations.AlterField(
            model_name='donation',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='core.recipient'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='goal_amount',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.1'), max_digits=18),
        ),
        migrations.AddIndex(
            model_name='socialdonation',
            index=models.Index(fields=['donor_address', '-created_at'], name='core_social_donor_a_dfe937_idx'),
        ),
        migrations.AddIndex(
            model_name='socialdonation',
            index=models.Index(fields=['recipient_address', '-created_at'], name='core_social_recipie_ceafaa_idx'),
        ),
        migrations.AddIndex(
            model_name='socialdonation',
            index=models.Index(fields=['is_public', '-created_at'], name='core_social_is_publ_67699b_idx'),
        ),
        migrations.AddField(
            model_name='tokenreward',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile'),
        ),
        migrations.DeleteModel(
            name='DonationCampaign',
        ),
        migrations.AddIndex(
            model_name='pooldonation',
            index=models.Index(fields=['donor_address', '-created_at'], name='core_pooldo_donor_a_eb9f38_idx'),
        ),
        migrations.AddIndex(
            model_name='pooldonation',
            index=models.Index(fields=['pool', '-created_at'], name='core_pooldo_pool_id_e012e2_idx'),
        ),
    ]
