# Generated by Django 5.2.4 on 2025-08-09 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_donationpool_pooldonation_socialdonation_tokenreward_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='tokens_claimed',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tokens_earned',
        ),
    ]
