# Generated by Django 5.2.4 on 2025-08-09 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_userprofile_tokens_claimed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='points_earned',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='total_points',
        ),
        migrations.RemoveField(
            model_name='pooldonation',
            name='points_earned',
        ),
        migrations.RemoveField(
            model_name='socialdonation',
            name='points_earned',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='total_points',
        ),
        migrations.DeleteModel(
            name='TokenReward',
        ),
    ]
